services:
    redis-like:
        build: ./redis-like
        expose: ['4000']
        networks: [internal]

    api:
        build: ./kv-server
        ports: ['8080:3000']
        environment:
            REDIS_URL: http://redis-like:4000
        depends_on: [redis-like]
        networks: [internal]

networks:
    internal:
